### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ashl1** [w33ble/redux-promise-actions#4]
If you stopped maintaining the project, could I maintain this project?
What way should we proceed in? Should I be a maintainer for npm package too?

**Comment by w33ble** [comment]
I’d be open to making you a contributor and even just handing over the repo. I’m also not sure the best way to proceed though. What do you think about me making a new major version, with no code changes, and just adding a release note that there’s a new maintainer? That way any existing users won’t auto update and the changelog will have the message about the change when they go looking to upgrade.

**Comment by ashl1** [comment]
Sounds good. Thank you

**Comment by w33ble** [comment]
Sorry, I haven't forgotten about this, I've just been busy with a bunch of other things. I'll get this done soon.

**Comment by w33ble** [comment]
Hey @ashl1, I think given all the fallout from the event-stream handoff (see https://github.com/dominictarr/event-stream/issues/115 and https://github.com/dominictarr/event-stream/issues/116 if you're out of the loop), I think I'd rather you just publish a new module instead of handing over this one. I'm happy to add a deprecation notice on npm and github that point to your fork though.

**Comment by w33ble** [comment]
I'm going to close this. If you end up making a fork, let me know.
